// Code generated by "stringer -type responseType -linecomment ./redisstore"; DO NOT EDIT.

package redisstore

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[typeArray-1]
	_ = x[typeBulk-2]
	_ = x[typeInt-3]
	_ = x[typeNull-4]
}

const _responseType_name = "ArrayBulkIntNull"

var _responseType_index = [...]uint8{0, 5, 9, 12, 16}

func (i responseType) String() string {
	i -= 1
	if i < 0 || i >= responseType(len(_responseType_index)-1) {
		return "responseType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _responseType_name[_responseType_index[i]:_responseType_index[i+1]]
}
