name: Test

on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request:
    branches:
    - main

jobs:
  # unit runs the unit tests
  unit:
    strategy:
      fail-fast: false
      matrix:
        go:
        - '1.14'
        - '1.15'
        - '1.16'
        os:
        - 'macos-latest'
        - 'ubuntu-latest'
        - 'windows-latest'

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Lint
      run: make fmtcheck staticcheck spellcheck
      if: ${{ matrix.os == 'ubuntu-latest' && matrix.go == '1.16' }}

    - name: Test
      run: make test

  # build runs go build on the target platforms to ensure the runtime links are
  # correct.
  build:
    strategy:
      fail-fast: false
      matrix:
        goos:
        - 'darwin'
        - 'freebsd'
        - 'linux'
        - 'netbsd'
        - 'openbsd'
        - 'solaris'
        - 'windows'
        goarch:
        - 'amd64'

    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Build
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: go build ./...
